from utils import patch_apk


def build_apk(apk: str, out: str):
    patches = "bins/patches.mpp"
    cli = "bins/morphe-cli.jar"

    common_includes = [
        "Disable ads",
        "Hide suggested content",
        "Filter stories",
        "Open links externally",
        "Disable comments",
        "Disable explore",
        "Disable highlights",
        "Disable stories",
        "Disable analytics",
        "Disable discover people",
        "Hide reshare button",
        "Disable typing status",
        "View live anonymously",
        "View stories anonymously",
        "Sanitize share links",
        "Validate links",
        "Remove build expired popup",
        "Change like animation",
        "Clone",
        "Copy comment",
        "Save media comment",
        "Download voice message",
        "Make ephemeral media permanent",
        "Mark chat as read manually",
        "Disable video autoplay",
        "Disable swipe to create",
        "Hide group creation button on sharesheet",
        "Hide navigation buttons",
        "Hide notes tray",
        "Hide stories tray",
        "Limit feed to following profiles",
        "Disable double tap like",
        "Download media",
        "External downloader",
        "View DMs anonymously",
        "Improve image viewing",
        "Unlock developer options",
        "Unlock employee options",
        "Allow user network certificate",
        "More options on post",
        "Disable screenshot detection",
        "Disable Reels scrolling",
        "Remove empty bottom space",
        "Add settings",
        "Customise story ring size",
        "Customise story timestamp",
        "Disable story flipping",
        "View story mentions",
        "Stories audio autoplay",
        "Theme",
        "Unlock Plus benefits",
        "Friendship status indicator",
        "More options on profile",
        "Remove Ads",
        "Hide recommendation items",
        "Disable chirp font",
        "Hide bookmark icon in timeline",
        "Hide FAB Menu Buttons",
        "Hide immersive player",
        "Remove view count",
        "Hook feature flag",
        "Custom download folder",
        "Add ability to copy media link",
        "Clear tracking params",
        "Handle custom twitter links",
        "Custom sharing domain",
        "Legacy share links",
        "No shortened URL",
        "Log server response",
        "Change app icon",
        "Block redirecting to X Lite",
        "Bring back twitter",
        "Customize explore tabs",
        "Custom emoji font",
        "Custom font",
        "Customize Inline action Bar items",
        "Customize Navigation Bar items",
        "Customize notification tabs",
        "Customise post font size",
        "Customize profile tabs",
        "Customize default reply sorting",
        "Customize search tab items",
        "Customize side bar items",
        "Customize timeline top bar",
        "Customize search suggestions",
        "Disunify xchat system",
        "Dynamic color",
        "Hide FAB",
        "Import/Export login token",
        "More information on profile",
        "Hide Recommended Users",
        "Round off numbers",
        "Pause search suggestions",
        "Remove search suggestions",
        "Selectable Text",
        "Enable debug menu for posts",
        "Support external downloader",
        "Native downloader",
        "Native reader mode",
        "Share Tweet as Image",
        "Custom share menu",
        "Native translator",
        "Show changelogs",
        "Enable PiP mode automatically",
        "Enable Undo Posts",
        "Download patch",
        "Hide Banner",
        "Delete from database",
        "Disable auto timeline scroll on launch",
        "Control video auto scroll",
        "Enable force HD videos",
        "Hide community badges",
        "Hide hidden replies",
        "Hide badges from navigation bar icons",
        "Hide nudge button",
        "Hide post metrics",
        "Hide followed by context",
        "Hide Live Threads",
        "Remove premium upsell",
        "Show sensitive media",
        "Show post source label",
        "Show poll results",
        "Force enable translate",
        "Hide Community Notes",
        "Hide promote button",
        "Export all activities",
        "Change version code"
    ]

    common_excludes = []

    patch_apk(
        cli,
        patches,
        apk,
        includes=common_includes,
        excludes=common_excludes,
        out=out,
    )
